### ISSUE TITLE
how to run java-first minial?

### ISSUE THREAD

**Issue by xxiong95** [stefan-kolb/jaxws-samples#4]
so new to jax-ws
dont know how to run it
cannot find the main method

**Comment by stefan-kolb** [comment]
Please take a look at the README. For most examples there is no Main class but a WAR file will be build and deployed. You can use `gradlew java-first:minimal:war` to build the WAR file or `gradlew java-first:minimal:cargoRunLocal` to start a server automatically. For all other sub projects please adapt the cli call accordingly.
